{% set name = "click-completion" %}
{% set version = "0.5.2" %}
{% set sha256 = "5bf816b81367e638a190b6e91b50779007d14301b3f9f3145d68e3cade7bce86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - six
    - click
    - jinja2
    - enum34  # [ py < 30 ]
    - shellingham

test:
  imports:
    - click_completion

about:
  home: https://github.com/click-contrib/click-completion
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fish, Bash, Zsh and PowerShell completion for Click

  description: |
    Enhanced completion for Click
    Add automatic completion support for fish, Zsh, Bash and PowerShell to Click.
    All the supported shells are able to complete all the command line arguments
    and options defined with click. In addition, fish and Zsh are also displaying
    the options and commands help during the completion.
  doc_url: https://github.com/click-contrib/click-completion
  dev_url: https://github.com/click-contrib/click-completion

extra:
  recipe-maintainers:
    - epruesse
